### ISSUE TITLE
html entity amp; being inserted into urls?

### ISSUE THREAD

**Issue by ghost** [elrumordelaluz/svgson#16] opened 2019-03-20 20:44 UTC
It seems that svgson is adding amp; into my svg image urls where I have ampersands. I'm happy to cater to this but I'm not sure if it is intended or not?

**Comment by uisupply** [comment] 2019-03-20 21:00
it also seems that href property will be converted into xlink:href property which is deprecated and it seems that all evergreen browsers support href

**Comment by elrumordelaluz** [comment] 2019-03-20 21:16
Hi @uisupply, thanks for open the _Issue_.

Do you have the svg `input` you are using, or at least the parts interested to check on my end?
Thanks,

**Comment by uisupply** [comment] 2019-03-20 22:16
Hi! I will try and get a repro for you tomorrow. You can ignore my second comment about xlink, that was another lib.

**Comment by elrumordelaluz** [comment] 2019-05-30 11:10
Hi @ghost, is this _issue_ still happen, I can't reproduce what you mean. Closing for now, but feel free to re-open or open a new one in any case.

**Closed by elrumordelaluz** 2019-05-30 11:10 UTC
