### ISSUE TITLE
Is it possible to promisify svgson?

### ISSUE THREAD

**Issue by ueeieiie** [elrumordelaluz/svgson#3] opened 2018-03-12 22:37 UTC
Hey,
great library, 
I just ran into it today :)

Is it possible to `promisify` svgson method when working with **nodejs**?

it will for sure  have a good use for it 

thanx for sharing 👍 👍 👍

**Comment by elrumordelaluz** [comment] 2018-03-12 22:47
hey @ueeieiie, first of all thanks for using `svgson`.

Could you please take at [`svgson-next`](https://github.com/elrumordelaluz/svgson-next) which is the improved version, new `API` and so on.

It lacks _documentation_ for now, but I think is easy to understand taking a look at the [tests](https://github.com/elrumordelaluz/svgson-next/blob/master/src/index.test.js#L69-L193).

In case you need there is a [`compat` mode atrribute](https://github.com/elrumordelaluz/svgson-next/blob/master/src/index.test.js#L154-L164) to make a response with the same keys as `svgson`.

Feel free to ask anything related to the _switch_

**Comment by elrumordelaluz** [comment] 2018-03-16 09:02
@ueeieiie did `svgson-next` fits well for your _Issue_? 

In that case I'll close this _Issue_ but please let me know how was for you to have a _feedback_. 

Also I'll probably update the `README` to make clear the differences, roadmap, etc.

**Comment by j1mie** [comment] 2018-03-16 13:16
Hey there. I'm getting the following error when building icons using node 8.2.1 - not sure if related? If not I can open a separate issue.

<img width="1061" alt="screen shot 2018-03-16 at 13 14 49" src="https://user-images.githubusercontent.com/12685163/37522542-2445acba-291c-11e8-8b9f-87c4f4f53ae3.png">

**Comment by elrumordelaluz** [comment] 2018-03-16 13:44
@j1mie using `svgson` (what version) or `svgson-next`?

In any case, could you show a [gist](https://gist.github.com/) or something with code to understand what's happening?

Thanks!

**Comment by ueeieiie** [comment] 2018-03-16 13:53
@elrumordelaluz hey, sorry for not updating.

In the end, I changed the direction and worked without any dependencies.
I got confused about what are the ways I have for working with SVG's and was looking for all kind of  _**webpack loaders**_,  and different libraries.

I had to fetch some SVG's from the internet and create sort of a composed SVG output,
I ended up with just fetching the file as a string and parse it back into an XML with the Web API's DOMParser:

 `new DOMParser().parseFromString(stringContainingXMLSource, "image/svg+xml");`

**Comment by elrumordelaluz** [comment] 2018-03-16 14:02
cool @ueeieiie!

**Comment by j1mie** [comment] 2018-03-16 14:17
@elrumordelaluz Using svgson and running as an npm script in packages.json:

```js
"build:icons": "mkdir -p icons && svgson -i ./svg --pretty -t --svgo -o ./icons.json"
```

**Comment by elrumordelaluz** [comment] 2018-03-16 15:03
@j1mie I can't reproduce the error. With the same command I am obtaining this result: 

![svgson_example](https://user-images.githubusercontent.com/784056/37527519-805b2992-2932-11e8-9062-8523ebddde39.gif)

same using `npm scripts`

![cli](https://user-images.githubusercontent.com/784056/37527773-1cacef88-2933-11e8-81fc-3b300fa56603.gif)

in both cases using `v8.2.1` of node

Did you reduce the case for one _Icon_? In case you get the same eror, could you share the example _Icon_, just to reduce _use-cases_ and find the source of the problem

**Comment by j1mie** [comment] 2018-03-16 18:01
@elrumordelaluz Thanks for looking into this!

Appears that I'm getting the errors in non-TTY environments - Webstorm / also happens with Travis CI, sometimes, strangely?

`process.stdout.cursorTo is not a function`

Not sure if this is something you'd want to check for with [isTTY](https://nodejs.org/api/tty.html#tty_tty)? If so, I can help with a PR

**Comment by j1mie** [comment] 2018-03-16 18:12
See https://github.com/travis-ci/travis-ci/issues/7967

**Comment by j1mie** [comment] 2018-03-16 18:15
Could alternately give it a -q (quiet) option to skip output altogether!

**Comment by elrumordelaluz** [comment] 2018-03-16 19:33
@j1mie thanks for all the information!

Just curious, you are getting those errors only using _Webstorm_? using a `TTY` env works well for you?

A PR is pretty welcome! 
I'm not sure fully understand where could be helpful the `isTTY` _check_ but probably you could show me, with (or without) the PR.

**Comment by j1mie** [comment] 2018-03-16 19:40
@elrumordelaluz Using Webstorm, and in some cases, Travis (which prevents project from building)!

Not overly familiar with isTTY but I figure we could use it to check, before using `process.stdout.cursorTo` etc.

**Comment by elrumordelaluz** [comment] 2018-03-16 19:53
[yup](https://github.com/sindresorhus/cli-cursor/blob/master/index.js#L20-L22)

**Closed** 2018-03-21 08:41 UTC
